name: hello-world
description: say Hello World
inputs:
  issue-numbers:
    description: a number of issue or pull request, or an array of numbers of issues or pull requests in JSON format
    required: false
  search-query:
    description: If set, search the issues by the query
    required: false
  context:
    description: infer an issue or pull request(s) from the context
    required: true
    default: 'false'
  add-labels:
    description: label name(s) to add to issues or pull requests, in multi-line format
    required: false
  remove-labels:
    description: label name(s) to remove from issues or pull requests, in multi-line format
    required: false
  post-comment:
    description: comment body to create into issues or pull requests
    required: false
  append-or-update-body:
    description: update body of issues or pull requests
    required: false
  token:
    description: a token for GitHub API
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
