name: hello-world
description: say Hello World
inputs:
  issue-numbers:
    description: a number of issue or pull request, or an array of numbers of issues or pull requests in JSON format
    required: true
  add-labels:
    description: label name(s) to add to issues or pull requests, in multi-line format
    required: false
  remove-labels:
    description: label name(s) to remove from issues or pull requests, in multi-line format
    required: false
  post-comment:
    description: comment body to create into issues or pull requests
    required: false
  token:
    description: a token for GitHub API
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
